version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: complexcare
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: complexcare_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U complexcare -d complexcare_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://complexcare:password123@postgres:5432/complexcare_db
      - SESSION_SECRET=local-dev-session-secret
      - PORT=3000
      - GROQ_API_KEY=${GROQ_API_KEY}
      - UPLOAD_DIR=./uploads
      - LOG_LEVEL=debug
    volumes:
      - ./uploads:/app/uploads
      - ./:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data:
